services:
  deeplx-bot:
    image: missuo/deeplx-bot:latest
    container_name: telegram-translator-bot
    environment:
      - BOT_TOKEN=7678901968:AAGc64_cePa3Dxt8xaqwwmna9e7nKkQRoGI
      - TARGET_LANG=ZH
      - API_URL=https://deeplx-api.onrender.com/translate
      - IGNORE_LANGS=ZH
    restart: always

  # deeplx:
  #   image: ghcr.io/owo-network/deeplx:latest
  #   restart: always
  #   ports:
  #     - "1188:1188"
